# Imagen base ligera de Python
FROM python:3.10-slim

# Directorio de trabajo
WORKDIR /app

# 🔥 Dependencias necesarias para TorchVision y PIL
RUN apt-get update && apt-get install -y \
    libglib2.0-0 \
    libgl1 \
    && rm -rf /var/lib/apt/lists/*

# Copiar dependencias
COPY requirements.txt .

# Instalar dependencias del backend
RUN pip install --no-cache-dir -r requirements.txt

# Copiar todo el backend (incluye modelo .pt)
COPY . .

# Exponer el puerto interno del contenedor
EXPOSE 8000

# Comando de inicio del backend
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
